<?php
return [
    [
        "business_name" => "O'Pizzaiuolo",
        "email" => "pizzaiuolo@live.it",
        "password" => 'pizzaiuolo',
        "address" => 'Via Toledo, 8 - Napoli',
        "vat_number" => '12548951657',
        "description" => 'La pizza più buona di Napoli',
        "image" => '/images/pizza.png',
        "phone" => '3289568777',
        "opening_time" => '18:00:00',
        "closing_time" => '24:00:00',
        "closing_day" => 'Lunedì',
        "free_shipping" => '0',
        "shipping_price" => '2.99',
    ],
    [
        "business_name" => "Pizzeria da Ciro",
        "email" => "daciro@live.it",
        "password" => 'daciro',
        "address" => 'Via Napoli, 8 - Napoli',
        "vat_number" => '15548956657',
        "description" => 'La pizza più buona di Napoli',
        "image" => '/images/pizza.png',
        "phone" => '3289565477',
        "opening_time" => '10:00:00',
        "closing_time" => '23:00:00',
        "closing_day" => 'Lunedì',
        "free_shipping" => '1',
        "shipping_price" => '0.00',
    ],
    [
        "business_name" => "Hokkaido",
        "email" => "hokkaido@gmail.com",
        "password" => 'Hokkaido189',
        "address" => 'Piazza Giuseppe Verdi, 15 - Lecce',
        "vat_number" => '85416378925',
        "description" => 'Barche di sushi e tempura, anche nella formula all you can eat, in locale con cucina a vista e arredi minimal.',
        "image" => '/images/pizza.png',
        "phone" => '0832520615',
        "opening_time" => '19:30:00',
        "closing_time" => '23:30:00',
        "closing_day" => 'Lunedì',
        "free_shipping" => "0",
        "shipping_price" => '4.99',
    ],
    [
        "business_name" => "Pizzeria Samuele",
        "email" => "pizzeriasamuele@gmail.com",
        "password" => 'samuele00',
        "address" => 'Via G. Buonocore 41/43, Napoli, 80143',
        "vat_number" => '69542031025',
        "description" => 'Pizzeria napoletana',
        "image" => '/images/pizza.png',
        "phone" => '064389521',
        "opening_time" => '16:30:00',
        "closing_time" => '23:00:00',
        "closing_day" => 'Giovedi',
        "free_shipping" => '1',
        "shipping_price" => '0.00',
    ],
    [
        "business_name" => "Gluten Free",
        "email" => "glutenfree@live.it",
        "password" => 'glutenfree',
        "address" => 'Via Milano, 8 - Napoli',
        "vat_number" => '15587956887',
        "description" => 'Il cibo gluten free più buono di tutti',
        "image" => '/images/pizza.png',
        "phone" => '3209588477',
        "opening_time" => '10:00:00',
        "closing_time" => '23:00:00',
        "closing_day" => 'Martedì',
        "free_shipping" => '1',
        "shipping_price" => '0.00',
    ],
    [
        "business_name" => "Voglia di pizza",
        "email" => "vogliadipizza@live.it",
        "password" => 'vogliadipizza',
        "address" => 'Via Milano, 8 - Napoli',
        "vat_number" => '10000568487',
        "description" => "Un'ottima pizza",
        "image" => '/images/pizza.png',
        "phone" => '3205588454',
        "opening_time" => '12:00:00',
        "closing_time" => '24:00:00',
        "closing_day" => 'Mercoledì',
        "free_shipping" => '1',
        "shipping_price" => '0.00',
    ],
    [
        "business_name" => "Hachi Ristorante Giapponese",
        "email" => "hachi@gmail.com",
        "password" => 'hachi00',
        "address" => 'Via Luca Giordano 33, 80127, Napoli ',
        "vat_number" => '95100236654',
        "description" => 'Ristorante giapponese',
        "image" => '/images/pizza.png',
        "phone" => '03516974',
        "opening_time" => '10:50:00',
        "closing_time" => '22:30:00',
        "closing_day" => 'Martedi',
        "free_shipping" => '0',
        "shipping_price" => '2.99',
    ],
    [
        "business_name" => "La Pazzeria",
        "email" => "pazzeria@live.it",
        "password" => 'pazzeria',
        "address" => 'Via Molise, 8 - Milano',
        "vat_number" => '10855688879',
        "description" => "Un'ottima pizza",
        "image" => '/images/pizza.png',
        "phone" => '3205588454',
        "opening_time" => '11:00:00',
        "closing_time" => '24:00:00',
        "closing_day" => 'Martedì',
        "free_shipping" => '1',
        "shipping_price" => '0.00',
    ],
    [
        "business_name" => "Poke House",
        "email" => "pokehouse@live.it",
        "password" => 'pokehouse',
        "address" => 'Via Aurno, 8 - Milano',
        "vat_number" => '78855689979',
        "description" => 'Che pokè!',
        "image" => '/images/pizza.png',
        "phone" => '3475599454',
        "opening_time" => '11:00:00',
        "closing_time" => '24:00:00',
        "closing_day" => 'Lunedì',
        "free_shipping" => '0',
        "shipping_price" => '2.99',
    ],
    [
        "business_name" => "NaBeer Birroteca",
        "email" => "nabeer@gmail.com",
        "password" => 'nabeer00',
        "address" => 'Vico Sergente Maggiore 39, 80132, Napoli',
        "vat_number" => '46006998521',
        "description" => 'Birroteca artiginiale con cibi da strada.',
        "image" => '/images/pizza.png',
        "phone" => '3290134026',
        "opening_time" => '11:20:00',
        "closing_time" => '23:50:00',
        "closing_day" => 'Domenica',
        "free_shipping" => '1',
        "shipping_price" => '0.00',
    ],
    [
        "business_name" => "Shabnaz",
        "email" => "shabnaz@gmail.com",
        "password" => 'shaby00',
        "address" => 'Via Liborio Romano, 19, 73100 Lecce LE',
        "vat_number" => '87624159320',
        "description" => "Shabnaz l'indiano più famoso di tutti i tempi di Lecce",
        "image" => '/images/pizza.png',
        "phone" => '0290669391',
        "opening_time" => '19:00:00',
        "closing_time" => '23:50:00',
        "closing_day" => 'Venerdì',
        "free_shipping" => '1',
        "shipping_price" => '0.00',
    ],
    [
        "business_name" => "The Mexican",
        "email" => "mexican@live.it",
        "password" => 'mexican',
        "address" => 'Via Palermo, 8 - Roma',
        "vat_number" => '78858887979',
        "description" => 'Tacos e tortillas',
        "image" => '/images/pizza.png',
        "phone" => '3485997454',
        "opening_time" => '12:00:00',
        "closing_time" => '24:00:00',
        "closing_day" => 'Lunedì',
        "free_shipping" => '0',
        "shipping_price" => '2.99',
    ],

];
